/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WikiRouteImport } from './routes/wiki'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RoutinesRouteImport } from './routes/routines'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ModulesRouteImport } from './routes/modules'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as CompactRouteImport } from './routes/compact'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoutinesIndexRouteImport } from './routes/routines.index'
import { Route as ChatIndexRouteImport } from './routes/chat.index'
import { Route as ActivityIndexRouteImport } from './routes/activity.index'
import { Route as SettingsCategoryRouteImport } from './routes/settings.$category'
import { Route as ChatThreadIdRouteImport } from './routes/chat.$threadId'
import { Route as ActivityEntryIdRouteImport } from './routes/activity.$entryId'
import { Route as RoutinesIdRunRouteImport } from './routes/routines.$id.run'
import { Route as RoutinesIdHistoryRouteImport } from './routes/routines.$id.history'
import { Route as RoutinesIdEditRouteImport } from './routes/routines.$id.edit'

const WikiRoute = WikiRouteImport.update({
  id: '/wiki',
  path: '/wiki',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutinesRoute = RoutinesRouteImport.update({
  id: '/routines',
  path: '/routines',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesRoute = ModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const CompactRoute = CompactRouteImport.update({
  id: '/compact',
  path: '/compact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutinesIndexRoute = RoutinesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RoutinesRoute,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const ActivityIndexRoute = ActivityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ActivityRoute,
} as any)
const SettingsCategoryRoute = SettingsCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => SettingsRoute,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ChatRoute,
} as any)
const ActivityEntryIdRoute = ActivityEntryIdRouteImport.update({
  id: '/$entryId',
  path: '/$entryId',
  getParentRoute: () => ActivityRoute,
} as any)
const RoutinesIdRunRoute = RoutinesIdRunRouteImport.update({
  id: '/$id/run',
  path: '/$id/run',
  getParentRoute: () => RoutinesRoute,
} as any)
const RoutinesIdHistoryRoute = RoutinesIdHistoryRouteImport.update({
  id: '/$id/history',
  path: '/$id/history',
  getParentRoute: () => RoutinesRoute,
} as any)
const RoutinesIdEditRoute = RoutinesIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => RoutinesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRouteWithChildren
  '/chat': typeof ChatRouteWithChildren
  '/compact': typeof CompactRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/history': typeof HistoryRoute
  '/memory': typeof MemoryRoute
  '/modules': typeof ModulesRoute
  '/onboarding': typeof OnboardingRoute
  '/routines': typeof RoutinesRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/wiki': typeof WikiRoute
  '/activity/$entryId': typeof ActivityEntryIdRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/settings/$category': typeof SettingsCategoryRoute
  '/activity/': typeof ActivityIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/routines/': typeof RoutinesIndexRoute
  '/routines/$id/edit': typeof RoutinesIdEditRoute
  '/routines/$id/history': typeof RoutinesIdHistoryRoute
  '/routines/$id/run': typeof RoutinesIdRunRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compact': typeof CompactRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/history': typeof HistoryRoute
  '/memory': typeof MemoryRoute
  '/modules': typeof ModulesRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRouteWithChildren
  '/wiki': typeof WikiRoute
  '/activity/$entryId': typeof ActivityEntryIdRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/settings/$category': typeof SettingsCategoryRoute
  '/activity': typeof ActivityIndexRoute
  '/chat': typeof ChatIndexRoute
  '/routines': typeof RoutinesIndexRoute
  '/routines/$id/edit': typeof RoutinesIdEditRoute
  '/routines/$id/history': typeof RoutinesIdHistoryRoute
  '/routines/$id/run': typeof RoutinesIdRunRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRouteWithChildren
  '/chat': typeof ChatRouteWithChildren
  '/compact': typeof CompactRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/history': typeof HistoryRoute
  '/memory': typeof MemoryRoute
  '/modules': typeof ModulesRoute
  '/onboarding': typeof OnboardingRoute
  '/routines': typeof RoutinesRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/wiki': typeof WikiRoute
  '/activity/$entryId': typeof ActivityEntryIdRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/settings/$category': typeof SettingsCategoryRoute
  '/activity/': typeof ActivityIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/routines/': typeof RoutinesIndexRoute
  '/routines/$id/edit': typeof RoutinesIdEditRoute
  '/routines/$id/history': typeof RoutinesIdHistoryRoute
  '/routines/$id/run': typeof RoutinesIdRunRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/chat'
    | '/compact'
    | '/diagnostics'
    | '/history'
    | '/memory'
    | '/modules'
    | '/onboarding'
    | '/routines'
    | '/settings'
    | '/wiki'
    | '/activity/$entryId'
    | '/chat/$threadId'
    | '/settings/$category'
    | '/activity/'
    | '/chat/'
    | '/routines/'
    | '/routines/$id/edit'
    | '/routines/$id/history'
    | '/routines/$id/run'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compact'
    | '/diagnostics'
    | '/history'
    | '/memory'
    | '/modules'
    | '/onboarding'
    | '/settings'
    | '/wiki'
    | '/activity/$entryId'
    | '/chat/$threadId'
    | '/settings/$category'
    | '/activity'
    | '/chat'
    | '/routines'
    | '/routines/$id/edit'
    | '/routines/$id/history'
    | '/routines/$id/run'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/chat'
    | '/compact'
    | '/diagnostics'
    | '/history'
    | '/memory'
    | '/modules'
    | '/onboarding'
    | '/routines'
    | '/settings'
    | '/wiki'
    | '/activity/$entryId'
    | '/chat/$threadId'
    | '/settings/$category'
    | '/activity/'
    | '/chat/'
    | '/routines/'
    | '/routines/$id/edit'
    | '/routines/$id/history'
    | '/routines/$id/run'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRouteWithChildren
  ChatRoute: typeof ChatRouteWithChildren
  CompactRoute: typeof CompactRoute
  DiagnosticsRoute: typeof DiagnosticsRoute
  HistoryRoute: typeof HistoryRoute
  MemoryRoute: typeof MemoryRoute
  ModulesRoute: typeof ModulesRoute
  OnboardingRoute: typeof OnboardingRoute
  RoutinesRoute: typeof RoutinesRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
  WikiRoute: typeof WikiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wiki': {
      id: '/wiki'
      path: '/wiki'
      fullPath: '/wiki'
      preLoaderRoute: typeof WikiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routines': {
      id: '/routines'
      path: '/routines'
      fullPath: '/routines'
      preLoaderRoute: typeof RoutinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules': {
      id: '/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof ModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compact': {
      id: '/compact'
      path: '/compact'
      fullPath: '/compact'
      preLoaderRoute: typeof CompactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routines/': {
      id: '/routines/'
      path: '/'
      fullPath: '/routines/'
      preLoaderRoute: typeof RoutinesIndexRouteImport
      parentRoute: typeof RoutinesRoute
    }
    '/chat/': {
      id: '/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/activity/': {
      id: '/activity/'
      path: '/'
      fullPath: '/activity/'
      preLoaderRoute: typeof ActivityIndexRouteImport
      parentRoute: typeof ActivityRoute
    }
    '/settings/$category': {
      id: '/settings/$category'
      path: '/$category'
      fullPath: '/settings/$category'
      preLoaderRoute: typeof SettingsCategoryRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/chat/$threadId': {
      id: '/chat/$threadId'
      path: '/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/activity/$entryId': {
      id: '/activity/$entryId'
      path: '/$entryId'
      fullPath: '/activity/$entryId'
      preLoaderRoute: typeof ActivityEntryIdRouteImport
      parentRoute: typeof ActivityRoute
    }
    '/routines/$id/run': {
      id: '/routines/$id/run'
      path: '/$id/run'
      fullPath: '/routines/$id/run'
      preLoaderRoute: typeof RoutinesIdRunRouteImport
      parentRoute: typeof RoutinesRoute
    }
    '/routines/$id/history': {
      id: '/routines/$id/history'
      path: '/$id/history'
      fullPath: '/routines/$id/history'
      preLoaderRoute: typeof RoutinesIdHistoryRouteImport
      parentRoute: typeof RoutinesRoute
    }
    '/routines/$id/edit': {
      id: '/routines/$id/edit'
      path: '/$id/edit'
      fullPath: '/routines/$id/edit'
      preLoaderRoute: typeof RoutinesIdEditRouteImport
      parentRoute: typeof RoutinesRoute
    }
  }
}

interface ActivityRouteChildren {
  ActivityEntryIdRoute: typeof ActivityEntryIdRoute
  ActivityIndexRoute: typeof ActivityIndexRoute
}

const ActivityRouteChildren: ActivityRouteChildren = {
  ActivityEntryIdRoute: ActivityEntryIdRoute,
  ActivityIndexRoute: ActivityIndexRoute,
}

const ActivityRouteWithChildren = ActivityRoute._addFileChildren(
  ActivityRouteChildren,
)

interface ChatRouteChildren {
  ChatThreadIdRoute: typeof ChatThreadIdRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatThreadIdRoute: ChatThreadIdRoute,
  ChatIndexRoute: ChatIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface RoutinesRouteChildren {
  RoutinesIndexRoute: typeof RoutinesIndexRoute
  RoutinesIdEditRoute: typeof RoutinesIdEditRoute
  RoutinesIdHistoryRoute: typeof RoutinesIdHistoryRoute
  RoutinesIdRunRoute: typeof RoutinesIdRunRoute
}

const RoutinesRouteChildren: RoutinesRouteChildren = {
  RoutinesIndexRoute: RoutinesIndexRoute,
  RoutinesIdEditRoute: RoutinesIdEditRoute,
  RoutinesIdHistoryRoute: RoutinesIdHistoryRoute,
  RoutinesIdRunRoute: RoutinesIdRunRoute,
}

const RoutinesRouteWithChildren = RoutinesRoute._addFileChildren(
  RoutinesRouteChildren,
)

interface SettingsRouteChildren {
  SettingsCategoryRoute: typeof SettingsCategoryRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsCategoryRoute: SettingsCategoryRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRouteWithChildren,
  ChatRoute: ChatRouteWithChildren,
  CompactRoute: CompactRoute,
  DiagnosticsRoute: DiagnosticsRoute,
  HistoryRoute: HistoryRoute,
  MemoryRoute: MemoryRoute,
  ModulesRoute: ModulesRoute,
  OnboardingRoute: OnboardingRoute,
  RoutinesRoute: RoutinesRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
  WikiRoute: WikiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
